[project]
name = "ferc"
version = "0.1.0"
description = "FERC EQR Report Viewer Data Scraper"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.3",
    "requests>=2.28.0",
    "selenium>=4.9.0",
    "webdriver-manager>=4.0.0",
]